apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ad0v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ad0v
    app.kubernetes.io/part-of: tkrw-pr712-0075-0004-app
  name: devfile-sample-ad0v
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ad0v
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ad0v
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0004-tenant/tkrw-pr712-0075-0004-app/devfile-sample-ad0v@sha256:f1126e3f6334043179760ebbe4d570aed69bd79f6f8d95e2bcfb1fa96f7e2be2
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
